insert into books (id, name) values (1, 'War and Peace');
insert into books (id, name) values (2, 'Philosophy of Java');
insert into books (id, name) values (3, 'Сollection of jokes');
insert into authors (id, name) values (1, 'Lev Tolstoy');
insert into authors (id, name) values (2, 'Bruce Ekkel');
insert into authors (id, name) values (3, 'Ivanov Ivan');
insert into authors (id, name) values (4, 'Sidorov Dmitry');
insert into genres(id, name) values (1, 'Novel');
insert into genres(id, name) values (2, 'Military prose');
insert into genres(id, name) values (3, 'Tutorial');
insert into genres(id, name) values (4, 'Comedy');
insert into book_authors(book_id, author_id) values (1, 1);
insert into book_authors(book_id, author_id) values (2, 2);
insert into book_authors(book_id, author_id) values (3, 3);
insert into book_authors(book_id, author_id) values (3, 4);
insert into book_genres(book_id, genre_id) values (1, 1);
insert into book_genres(book_id, genre_id) values (1, 2);
insert into book_genres(book_id, genre_id) values (2, 3);
insert into book_genres(book_id, genre_id) values (3, 4);
insert into comments(id, book_id, text) values (1, 1, 'good book');
insert into comments(id, book_id, text) values (2, 1, 'poor book');