spring:
  batch:
    job:
      enabled: false
  shell:
    interactive:
      enabled: true

  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
    initialization-mode: always
    schema: classpath:schema.sql

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    generate-ddl: false
    database: h2
    show-sql: true
    hibernate:
     ddl-auto: none

  data:
    mongodb:
      uri: mongodb://localhost
      port: 0
      database: library

server:
  port: 8089