drop table if exists comments;

drop table if exists books;

drop table if exists authors;

drop table if exists genres;

create table authors (id bigint generated by default as identity primary key, name varchar(255), unique key authors_uk1 (name));

create table genres (id bigint generated by default as identity primary key, name varchar(255),unique key genres_uk1 (name));

create table books (id bigint generated by default as identity primary key, name varchar(255), author_id bigint, genre_id bigint,
  unique key books_uk1 (name),
  foreign key (author_id) references authors (id),
  foreign key (genre_id) references genres (id));

create table comments (id bigint generated by default as identity primary key, book_id bigint, text varchar(255), create_date date,
  foreign key (book_id) references books (id));