drop table if exists books;
drop table if exists authors;
drop table if exists genres;
drop table if exists comments;
create table books (id bigint generated by default as identity primary key, name varchar(255), author_id bigint, genre_id bigint);
create table authors (id bigint generated by default as identity primary key, name varchar(255));
create table genres (id bigint generated by default as identity primary key, name varchar(255));
create table comments (id bigint generated by default as identity primary key, book_id bigint, text varchar(255));