app:
  server-email: spring.project@mail.ru
  admin-email: spring.project@mail.ru

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
    initialization-mode: always
    schema: classpath:schema.sql

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

    show-sql: true

  mail:
    host: smtp.mail.ru
    port: 465
    # логин и пароль для почты, через которую сервер отправляет письма
    username: spring.project
    password: Otus201911
    protocol: smtps
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true

  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    ROOT: INFO

server:
  port: 8888