-- скрипт для создания схемы
drop table if exists accounts;
drop table if exists clients;
drop table if exists credits;
drop table if exists pay_documents;
drop table if exists account_types;
drop table if exists eods;
drop table if exists prepayment_applications;
drop table if exists user_roles;
drop table if exists users;

-- клиенты
create table clients(
                     id          bigint generated by default as identity primary key,
                     last_name   varchar(255),
                     middle_name varchar(255),
                     first_name  varchar(255),
                     passport_id varchar(50),
                     email       varchar(255)
                    );

-- договоры
create table credits(
                     id                     bigint generated by default as identity primary key,
                     client_id              bigint,
                     application_id         varchar(255),
                     percent_rate           decimal(10, 3),
                     status                 varchar(255),
                     sum                    decimal(20, 2),
                     reg_payment            decimal(20, 2),
                     next_stmt_date         date,
                     issue_date             date,
                     stmt_day               smallint,
                     overdue_fee            decimal(20, 2),
                     last_processed_date    date,
                     last_processed_message varchar(32000)
                    );

-- счета договоров
create table accounts(
                      id           bigint generated by default as identity primary key,
                      credit_id    bigint,
                      account_type bigint,
                      balance      decimal(33, 15)
                     );

-- типы счетов
create table account_types(
                           id                bigint generated by default as identity primary key,
                           code              varchar(50),
                           repayment_order   int,
                           is_credit_account boolean
                          );

-- платежки
create table pay_documents(
                           id                  bigint generated by default as identity primary key,
                           type                varchar(50),
                           eod_date            date,
                           operation_date      timestamp,
                           account_id_dt       bigint,
                           account_id_kt       bigint,
                           external_account_dt varchar(50),
                           external_account_kt varchar(50),
                           sum                 decimal(33, 15),
                           status              varchar(50),
                           is_external         boolean
                          );

-- опер.дни
create table eods(
                  id            bigint generated by default as identity primary key,
                  date             date,
                  open_time        timestamp,
                  close_time_start timestamp,
                  close_time_end   timestamp,
                  status           varchar(50)
                 );

-- заявки на досрочное погашение
create table prepayment_applications (
                                      id          bigint generated by default as identity primary key,
                                      create_date timestamp,
                                      credit_id   bigint,
                                      is_full     boolean,
                                      sum         decimal(20,2),
                                      date        date,
                                      status      varchar(50)
                                     );

-- пользователи
CREATE  TABLE users (
  username VARCHAR(45) NOT NULL,
  password VARCHAR(60) NOT NULL,
  enabled boolean NOT NULL DEFAULT true,
  PRIMARY KEY (username));

-- роли
CREATE TABLE user_roles (
  id bigint generated by default as identity primary key,
  username varchar(45) NOT NULL,
  role varchar(45) NOT NULL,
  UNIQUE(role,username),
  CONSTRAINT fk_username FOREIGN KEY (username) REFERENCES users (username));

-- индексы
CREATE INDEX clients_passport_idx ON clients(passport_id);
CREATE INDEX clients_name_name_idx ON clients(last_name, first_name, middle_name);
CREATE INDEX credits_client_idx ON credits(client_id);
CREATE INDEX credits_next_stmt_date_idx ON credits(next_stmt_date);
CREATE INDEX credits_last_processed_date_idx ON credits(last_processed_date);
CREATE INDEX credits_status_date_idx ON credits(status);
CREATE INDEX accounts_credit_idx ON accounts(credit_id);
CREATE INDEX pay_documents_eod_date_status_idx ON pay_documents(eod_date, status);
CREATE INDEX pay_documents_account_id_dt_idx ON pay_documents(account_id_dt);
CREATE INDEX pay_documents_account_id_kt_idx ON pay_documents(account_id_kt);
CREATE INDEX pay_eods_date_idx ON eods(date);
CREATE INDEX pay_eods_status_idx ON eods(status);
CREATE INDEX prepayment_applications_date_idx ON prepayment_applications(date);