drop table if exists accounts;
drop table if exists clients;
drop table if exists credits;
drop table if exists pay_documents;

create table clients(
                     id          bigint generated by default as identity primary key,
                     last_name   varchar(255),
                     middle_name varchar(255),
                     first_name  varchar2(255),
                     passport_id varchar2(50),
                     email       varchar2(255)
                    );

create table credits(
                     id                     bigint generated by default as identity primary key,
                     client_id              bigint,
                     application_id         varchar(255),
                     percent_rate           double(3),
                     status                 varchar2(255),
                     sum                    double(2),
                     reg_payment            double(2),
                     next_stmt_date         date,
                     issue_date             date,
                     stmt_day               tinyint,
                     overdue_fee            double(2),
                     last_processed_date    date,
                     last_processed_message varchar2(32000)
                    );

create table accounts(
                      id           bigint generated by default as identity primary key,
                      credit_id    bigint,
                      account_type bigint,
                      balance      double(15)
                     );

create table account_types(
                           id                bigint generated by default as identity primary key,
                           code              varchar2(50),
                           repayment_order   int,
                           is_credit_account boolean
                          );

create table pay_documents(
                           id                  bigint generated by default as identity primary key,
                           type                varchar(50),
                           eod_date            date,
                           operation_date      timestamp,
                           account_id_dt       bigint,
                           account_id_kt       bigint,
                           external_account_dt varchar(50),
                           external_account_kt varchar(50),
                           sum                 double(15),
                           status              varchar(50),
                           is_external         boolean
                          );

create table eods(
                  id            bigint generated by default as identity primary key,
                  date             date,
                  open_time        timestamp,
                  close_time_start timestamp,
                  close_time_end   timestamp,
                  status           varchar2(50)
                 );

create table prepayment_applications (
                                      id          bigint generated by default as identity primary key,
                                      create_date timestamp,
                                      credit_id   bigint,
                                      is_full     boolean,
                                      sum         double(2),
                                      date        date,
                                      status      varchar2(50)
                                     );